<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYhprxvc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYhprxvc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYhprxvc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYhprxvc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYhprxvc\appProdProjectContainer([
    'container.build_hash' => 'Yhprxvc',
    'container.build_id' => 'd5cd8b11',
    'container.build_time' => 1614342549,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYhprxvc');
