<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxtooxy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxtooxy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBxtooxy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBxtooxy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBxtooxy\appProdProjectContainer([
    'container.build_hash' => 'Bxtooxy',
    'container.build_id' => '048a6213',
    'container.build_time' => 1614867147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxtooxy');
